name: Bug report
description: Report a bug or unexpected behavior in Venumity UI
title: "[Bug]: "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug in **Venumity UI**  
        Please provide as much detail as possible so we can fix it quickly.

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Clearly explain the issue you’re experiencing and also write about your solution for that.
      placeholder: What went wrong ?
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      options:
        - label: I have searched existing issues to ensure this bug hasn’t been reported.
          required: true
        - label: I am using the latest version of Venumity UI.
          required: true
        - label: I have provided enough information to reproduce the issue.
          required: true