export const BASE_IMAGES = [
  "/thumbnails/3d-scatter-plot.png",
  "/thumbnails/action-alert.png",
  "/thumbnails/area-sparkline.png",
  "/thumbnails/bar-sparkline.png",
  "/thumbnails/basic-accordion.png",
  "/thumbnails/basic-area-chart.png",
  "/thumbnails/basic-bar-chart.png",
  "/thumbnails/basic-inline-loader.png",
  "/thumbnails/basic-line-chart.png",
  "/thumbnails/basic-pie-chart.png",
  "/thumbnails/basic-radar-chart.png",
  "/thumbnails/basic-scatter-plot.png",
  "/thumbnails/bento-grid-1.png",
  "/thumbnails/carousel-testimonial-2.png",
  "/thumbnails/charts-dashboard.png",
  "/thumbnails/company-testimonial.png",
  "/thumbnails/connection-status-badge.png",
  "/thumbnails/custom-dots-line-chart.png",
  "/thumbnails/custom-label-line-chart.png",
  "/thumbnails/dashboard-skeleton-loader.png",
  "/thumbnails/donut-pie-chart.png",
  "/thumbnails/dots-color-line-chart.png",
  "/thumbnails/dots-line-chart.png",
  "/thumbnails/enhance-mail.png",
  "/thumbnails/faq-1.png",
  "/thumbnails/filled-radar-chart.png",
  "/thumbnails/full-page-loader.png",
  "/thumbnails/gradient-area-chart.png",
  "/thumbnails/background-gradient-spotlight.png",
  "/thumbnails/grid-loader-1.png",
  "/thumbnails/grouped-bar-chart.png",
  "/thumbnails/horizontal-bar-chart.png",
  "/thumbnails/label-line-chart.png",
  "/thumbnails/label-radial-chart.png",
  "/thumbnails/line-sparkline.png",
  "/thumbnails/linear-line-chart.png",
  "/thumbnails/masonry-image-gallery.png",
  "/thumbnails/mixed-bar-chart.png",
  "/thumbnails/modal-alert.png",
  "/thumbnails/multi-area-chart.png",
  "/thumbnails/multi-pulse-loader.png",
  "/thumbnails/multiple-line-chart.png",
  "/thumbnails/multiple-open-accordion.png",
  "/thumbnails/nested-accordion.png",
  "/thumbnails/percent-area-chart.png",
  "/thumbnails/personal-panel-1.png",
  "/thumbnails/popup-1.png",
  "/thumbnails/premium-container.png",
  "/thumbnails/premium-wave-loader.png",
  "/thumbnails/pricing-table-1.png",
  "/thumbnails/product-card-3.png",
  "/thumbnails/profile-card-1.png",
  "/thumbnails/range-sparkline.png",
  "/thumbnails/real-time-filterable-table.png",
  "/thumbnails/ring-spinner.png",
  "/thumbnails/scatter-sparkline.png",
  "/thumbnails/setp-line-chart.png",
  "/thumbnails/shiny-button-loader.png",
  "/thumbnails/snackbar-2.png",
  "/thumbnails/sortable-table.png",
  "/thumbnails/spline-area-chart.png",
  "/thumbnails/stacked-area-chart.png",
  "/thumbnails/stacked-bar-chart.png",
  "/thumbnails/standard-alert.png",
  "/thumbnails/standard-footer.png",
  "/thumbnails/standard-navbar.png",
  "/thumbnails/steps-accordion.png",
  "/thumbnails/sticky-glass-navbar.png",
  "/thumbnails/summary-block.png",
  "/thumbnails/tiered-pricing-card.png",
  "/thumbnails/toast-1.png",
  "/thumbnails/winloss-sparkline.png"
];


export const SOCIAL_LINKS = [
  {
    src: "/social/instagram.png",
    alt: "Instagram",
    href: "https://instagram.com/thevinayakgore",
    rotate: "-rotate-12",
    left: "left-0",
  },
  {
    src: "/social/twitter.png",
    alt: "Twitter",
    href: "https://twitter.com/thevinayakgore",
    rotate: "-rotate-10",
    left: "left-10",
  },
  {
    src: "/social/threads.png",
    alt: "Threads",
    href: "https://threads.net/@thevinayakgore",
    rotate: "-rotate-8",
    left: "left-20",
  },
  {
    src: "/social/linkedin.png",
    alt: "LinkedIn",
    href: "https://linkedin.com/in/thevinayakgore",
    rotate: "-rotate-6",
    left: "left-30",
  },
  {
    src: "/social/reddit.png",
    alt: "Reddit",
    href: "https://reddit.com/user/thevinayakgore",
    rotate: "-rotate-4",
    left: "left-40",
  },
  {
    src: "/social/facebook.png",
    alt: "Facebook",
    href: "https://facebook.com/thevinayakgore",
    rotate: "-rotate-2",
    left: "left-50",
  },
  {
    src: "/social/dribbble.png",
    alt: "Dribbble",
    href: "https://dribbble.com/thevinayakgore",
    rotate: "rotate-0",
    left: "left-60",
  },
  {
    src: "/social/linktree.png",
    alt: "Linktree",
    href: "https://linktr.ee/thevinayakgore",
    rotate: "rotate-2",
    left: "left-70",
  },
  {
    src: "/social/upwork.png",
    alt: "Upwork",
    href: "https://www.upwork.com/freelancers/~015ebda394a4770870?mp_source=share",
    rotate: "rotate-4",
    left: "left-80",
  },
  {
    src: "/social/fiverr.jpg",
    alt: "Fiverr",
    href: "https://www.fiverr.com/thevinayakgore?public_mode=true",
    rotate: "rotate-6",
    left: "left-90",
  },
  {
    src: "/social/gumroad.png",
    alt: "Gumroad",
    href: "https://gumroad.com/thevinayakgore",
    rotate: "rotate-8",
    left: "left-100",
  },
  {
    src: "/social/youtube.png",
    alt: "YouTube",
    href: "https://youtube.com/@thevinayakgore",
    rotate: "rotate-10",
    left: "left-110",
  },
  {
    src: "/social/github.webp",
    alt: "GitHub",
    href: "https://github.com/thevinayakgore",
    rotate: "rotate-12",
    left: "left-120",
  },
  {
    src: "/social/happenstance.png",
    alt: "Happenstance",
    href: "https://happenstance.ai/u/thevinayakgore",
    rotate: "rotate-14",
    left: "left-130",
  },
];